---
apiVersion: apps/v1
kind: Deployment 
metadata:
  namespace: houcemapp
  name: maven-deploy
  labels: 
    app: maven
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: maven
        image: houcemdevops/maven-app:8
---
apiVersion: v1
kind: Service
metadata:
  name: svc-maven
  namespace: houcemapp
spec:
  selector:
    app: maven
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
